config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :posts
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :body, presence :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.new(product_params)

        if @post.save
            flash[:notice] = "saved successfully"
            redirect_to @post
        else 
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(title: params[:post][:title], body: params[:post][:body])
            redirect_to post_path(@post)
            
        else
            render :edit, :status, :unprocessable_entity

        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExerciseClass</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
     <% end %> 
  </body>
</html>

app/views/layouts/posts/edit.html.erb
<%= form_with(model: @post) do |form| %>

<%= if @post.errors.any? %>
    <%= @post.errors.full_messages.each do |message| %>
        <div><%= message %></div>
    <%= end %>
<%= end %>

<div>
<%= form.label :title%>
<%= forms.text_field :title %>
</div>

<div>
<%= form.label :body%>
<%= forms.text_field :body %>
</div>

<div>
<%= form.submit%>
<%= end %>

app/views/layouts/posts/index.html.erb
<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
  <h3><%=post.title%></h3>
  <p><%= post.body%></p>
   
  <% end %>

app/views/layouts/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>


<%= form_with(model: @post) do |form| %>
<div>
<%= form.label :title %>
<%= form.text_field :title %>
</div>
<div>
<%= form.label :body %>
<%= form.text_field :body %>
</div>

<%= form.submit %>
<% end %>

app/views/layouts/posts/show.html.erb
<%= render @post%>

<div>
    <%= link_to "Edit this post", edit_post_path(@post)%>
    <%= link_to "Back to post", post_path %>
    <%= button_to "Destroy this post", @post, method :delete %>
</div>